* Merseburg Incantation                                            :TOC_5_gh:
  - [[#introduction-and-overview][Introduction and Overview]]
    - [[#why-merseburg-incantation][Why "Merseburg Incantation"?]]

** Introduction and Overview
   The Merseburg Incantation (German: Die Merseburger
   Zauberspruch, and hereafter referred to as 'MZ') is
   a simple way to divide the processing of a
   (presumably large) collection across multiple
   threads. Ideally, you want to divide the work among
   a thread count equalling 1x to 2x the number of
   cores on the machine it's running on.

   An effort is made here to make the use MZ as painless
   and easy as possible, using reasonsable defaults. MZ will
   query std::thread::hardware_concurrency to get the number
   of threads possible, and if this returns a '0', will default to 4.

*** Why "Merseburg Incantation"?
    I usually wind up consulting Greek Mythology when I want to find a snazzy name
    for a project. But since I am fascinated by Germany and its long and rich history,
    I decided to look for something in German Mythology instead. 

    Not much survives from 9th century Germany, alas. If you are interested, please
    see:

    https://en.wikipedia.org/wiki/Merseburg_charms

    and

    https://althochdeutsch.fandom.com/de/wiki/Merseburger_Zauberspr%C3%BCche
